# Generated by Django 3.2.5 on 2021-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javascript', models.CharField(max_length=15)),
                ('python', models.CharField(max_length=12)),
                ('year', models.PositiveSmallIntegerField()),
                ('date_of_enroll', models.DateField()),
                ('school', models.CharField(max_length=15)),
                ('courseid', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
