# Generated by Django 3.2.4 on 2021-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=12)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('district', models.CharField(max_length=15)),
                ('trainertid', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('course_name', models.CharField(max_length=20)),
                ('trainerbio', models.CharField(max_length=150)),
            ],
        ),
    ]
